### ISSUE TITLE
Upgrade does not apply from 0.1.0 to 0.2.0

### ISSUE THREAD

**Issue by jonathanweinberg** [hassio-addons/addon-ide#10]
# Problem/Motivation

Upgrade from `0.1.0` to `0.2.0` continues to show up. Version does not change after clicking upgrade.

## Expected behavior

The add-on to update to `0.2.0`

## Actual behavior

The update continually shows as available but stays at version `0.1.0`

This is found in the Hass.IO system log:

```
18-05-20 19:19:17 INFO (SyncWorker_16) [hassio.docker.interface] Stop hassioaddons/ide-armhf docker application
18-05-20 19:19:19 INFO (SyncWorker_16) [hassio.docker.interface] Clean hassioaddons/ide-armhf docker application
18-05-20 19:19:21 INFO (SyncWorker_14) [hassio.docker.interface] Update docker 0.1.0 with hassioaddons/ide-armhf:0.2.0
18-05-20 19:19:21 INFO (SyncWorker_14) [hassio.docker.interface] Pull image hassioaddons/ide-armhf tag 0.2.0.
18-05-20 19:19:22 ERROR (SyncWorker_14) [hassio.docker.interface] Can't install hassioaddons/ide-armhf:0.2.0 -> 404 Client Error: Not Found ("manifest for hassioaddons/ide-armhf:0.2.0 not found").
```

## Steps to reproduce

Attempt upgrade I suppose.

## Proposed changes

N/A

**Comment by freddykat** [comment]
I have the same issue as you.
There's a way to manually update?

**Comment by frenck** [comment]
Support for ARM-based processors has been dropped. (This includes Raspberry Pi's).

Please read the official announcement here: 

<https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck>

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/frenck/200/13184_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck">Community Hass.io Add-on: IDE, based on Cloud9</a></strong></div><div>🎉 Release v0.2.0 This release is exciting, at least, for me it is. I’ve been working on this for months! And for you? Well, a couple of things…  So what did change? I’ve updated the workflows of the Community Hass.io Add-ons project. Things include:   Replaced CircleCI and CodeClimate. We are now using GitLab CI, backed by a couple of custom servers building and testing these add-ons. All add-ons are now scanned during built and release by Clair to prevent security issues in our add-ons. A...</div></blockquote>
