### ISSUE TITLE
Can't install or upgrade to 0.2.0 

### ISSUE THREAD

**Issue by bruhautomation** [hassio-addons/addon-ide#12]
Yo, thanks for your work on this project! Love the Cloud9 implementation for HA! Super nice. 

I've been running 0.1.0 without issue for a while, but I'm having no success either A) installing 0.2.0 on a clean instance of Hass.IO in my dev environment. Or B) upgrading from 0.1.0 to 0.2.0 in my other HASS.IO instances. 

When I click either the "upgrade" or "install" buttons, it bounces for a few seconds and nothing happens. 

![cloud ide fail](https://user-images.githubusercontent.com/14144928/40879911-fc61ea28-6675-11e8-963b-2fdae23ff410.gif)

Cheers!

**Comment by chaim007** [comment]
The same problem with me..

**Comment by cpantu** [comment]
I have the same problem, i can't upgrade, i made uninstall and now i can't install. 
Thanks for the great work!

**Comment by frenck** [comment]
Hi there @bruhautomation, @chaim1986, @cpantu,

Support for Raspberry Pi was dropped initially since there where several issues with it.
It seems like I've found the golden ticket, so I expect to release a new version with ARM (Raspberry Pi) support soon.

**Comment by frenck** [comment]
Fixed! Just released v0.3.0 which addresses this issue.

Thank you for the report.
