### ISSUE TITLE
Ide Addon won't start

### ISSUE THREAD

**Issue by blackgold9** [hassio-addons/addon-ide#14]
# Problem/Motivation

I can't start the IDE. 
## Expected behavior

Ide addon starts.

## Actual behavior

It fails with the error: 
ERROR: unsatisfiable constraints:
  php7-7.2.6-r0:
    masked in: @edge
    satisfies: world[php7-cli]
FATAL: Failed installing package php7-cli

## Steps to reproduce

I have hass.io installed on an intel nuc running ubuntu

**Comment by frenck** [comment]
Hi there @blackgold9,

Thank you for your bug report.
I wonder, PHP is not part of the add-on, so I guess you've installed it manually.

Could you please share you add-on configuration?

../Frenck
