### ISSUE TITLE
Uploading is allowed to the workspace directory

### ISSUE THREAD

**Issue by GrandadEvans** [hassio-addons/addon-ide#15]
# Problem/Motivation

> Using the *File->Upload local files...* option can upload files and folders to the */workspace* directory, this will result in those entities being lost on reboot.
This is also unintentional behaviour. I was successfully uploading to the config dir but at some point, it just switched to the */workspace* dir without me checking as I was uploading many directories/files.

## Expected behavior

> If a user tries to upload to the */workspace* dir the action should not be allowed and user told to check the dir they are trying to upload to.

## Actual behaviour

> The user (me) didn't see the *"upload to folder:/"* had changed from *"Upload to folder :/config"*. This meant the entities were uploaded to the */workspace* dir.
When one tries to drag and drop the entities into the config dir a popup says:

> "cannot move files/icloud" and a red bar at the top says
> "Failed to rename folder 'icloud' to 'icloud'. EXDEV: cross-device link not permitted, rename '/workspace/icloud' -> '/workspace/config/icloud'."

## Steps to reproduce

1. Select the root *"workspace"* dir in the left-hand side directory listings.
1. Click *"File" -> "Upload local files..."*
1. Make sure the *"Upload to folder"* is set to *"/"* and not *config*
1. Select either *"Select files"* or *"Select folder"* and upload a file or folder
1. Try to drag and drop the newly uploaded file/folder to the *config* dir

## Proposed changes

This is by @frenck from the Discord chat
> To solve the moving part
> I think the add-on should not use a symlink for the "known" folder, but probably a bind mount
> secondly, we should set some permissions bits on the workspace directory itself, to prevent writing access
> To be able to bind though, we would need specific docker permissions (FTP add-on uses it)

**Comment by frenck** [comment]
Remove the stale...
