### ISSUE TITLE
addon start error on pi3

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-ide#16]
![screen shot 2018-06-13 at 20 30 30](https://user-images.githubusercontent.com/3314004/41383929-8d06aa2e-6f49-11e8-9141-5f80a60deeaf.png)
# Problem/Motivation
i have  updated from previous version ( was working fine) , now i get the following error:
error during start 
> TypeError: css.split is not a function

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by gnkarn** [comment]
Frenck, continue testing ....  it works fine on Safari, but wont open on mac Chrome .

**Comment by frenck** [comment]
@gnkarn Flush cache? Have you tried it in incognito?

**Comment by gnkarn** [comment]
Frenck , yes i tried cleaning cache , but same  results .

**Comment by frenck** [comment]
@gnkarn, sorry to hear it is not resolved for ya.

Could you please provide me the exact version details of your Chrome and OS?
This allows me to do some testing on, for example, browserstack.com.

![bitmoji](https://render.bitstrips.com/v2/cpanel/2a4844d2-596c-44df-a12e-76f27811b31a-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)
