### ISSUE TITLE
Download files/project does not work on Chrome Browser in Windows

### ISSUE THREAD

**Issue by slomanl1** [hassio-addons/addon-ide#17]
# Problem/Motivation

> Downloads should work on any web browser.

## Expected behavior

> When a user selects a singe file/multiple files or 'Download Project' the files should be downloaded to the host computer to the selected download folder in he browser settings

## Actual behavior

> When files are selected for download no response occurs. No error message appears in the Home Assistant los either

## Steps to reproduce

>1. Open Chrome browser to IDE add-on. 
   2. Select a file or multiple files and right-click download files.

## Proposed changes

> Please investigate.
> You can us Edge browser on windows. I have not tested it on Firefox.

**Comment by frenck** [comment]
The main issue with this is, I do not have access to Windows machines 😩

**Comment by slomanl1** [comment]
Can you try it on a Chrome browser on another platform?

**Comment by frenck** [comment]
@slomanl1 I did... it works...

**Comment by ludeeus** [comment]
@slomanl1 Do you still have an issue with this?
I use that functionality on a Windows 10 machine (with Chrome) almost daily.

**Comment by slomanl1** [comment]
Yes I still cannot download when using Chrome. Edge works fine. 
Larry

**Comment by ludeeus** [comment]
@slomanl1 Can you try that with incognito mode on (ctrl+shift+n)
It sounds like you have disabled something in your browser

**Comment by ludeeus** [comment]
@slomanl1 Did you try the last suggestion?

**Comment by beemeeup** [comment]
Just found the addon and installed it.

I the checked this issue.

Downloading a file works for me in chrome

Windows 10 Pro build 1803
Version 68.0.3440.106 (Offizieller Build) (64-Bit)

**Comment by frenck** [comment]
I've tested this now as well (using browser stack) and was unable to reproduce it.
I'm closing this issue for now.
