### ISSUE TITLE
Instructions Do Not Work

### ISSUE THREAD

**Issue by jeremyakers** [hassio-addons/addon-ide#18]
# Problem/Motivation

Instructions leave out username/password and SSL requirements.

## Expected behavior

For the add on to start per instructions.

## Actual behavior

Add on fails to start with error: "FATAL: You need to set a username!"
After adding username and password: FATAL: The configured certfile is not found

## Steps to reproduce

Install add-on per instructions at: https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810
Which as of Sept 6th currently say:

    1.) Add our Hass.io add-ons repository 213 to your Hass.io 56 instance.
    Add the following URL: https://github.com/hassio-addons/repository
    2.) Install the “IDE” add-on.
    3.) Start the “IDE” add-on.
    4.) Check the logs of the “IDE” add-on to see if everything went well.
    5.) Surf to your Hass.io 56 instance and use port 8321
    (e.g. http://hassio.local:8321).

## Proposed changes

Update instructions with actual steps needed to install, configure and start Add-on.

<blockquote><img src="https://community-home-assistant-assets.s3-us-west-2.amazonaws.com/optimized/2X/b/b27599dfa02621d5662d64e2726ba47dd1315d6d_1_32x32.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810">Community Hass.io Add-on: IDE, based on Cloud9</a></strong></div><div>This add-on is provided by the Community Hass.io Add-ons project.             About  This add-on will give you a full blown IDE in your Home Assistant web interface and allows you to edit every aspect of your setup with ease. It will provide you with the same experience of editing your configurations as if you’d use a combination of a desktop editor and Samba.  It is based on Cloud9 IDE which is an online integrated development environment. It supports hundreds of programming languages, includ...</div></blockquote>

**Comment by frenck** [comment]
The instructions help you to check the logs to see if the requirements are met.
So I don't see this personally.

Especially: `FATAL: The configured certfile is not found`. This is outside the scope of the add-on.

**Comment by jeremyakers** [comment]
Absolutely astounding. Your instructions make it sound like all you have to do is click "Install" and then "Start" and completely leave out the fact that you need to configure a username and password, generate certificates, and don't you think it would be helpful to mention where the certfiles need to be placed?

Your instructions could just as well be written as: "Good luck figuring it out on your own" and that would still be *more* helpful.

**Comment by frenck** [comment]
Wow, that comment was absolutely not called for.

Every option of the add-on is documented. Each environment is different as well.
All my add-ons have a sane and secure default, for example, having SSL enabled by default. If you don't have an SSL certificate, just disable SSL (but hey, you should have SSL on your system in the first place, read Home Assistant security documentation and recommendations).

Anyways, feel free to open a PR with "better" instructions or, if you don't like this at all, be sure to uninstall all the community addons since you are going to have a hard time.
