### ISSUE TITLE
Unable to connect to Cloud9 IDE

### ISSUE THREAD

**Issue by mayankraichura** [hassio-addons/addon-ide#21]
# Problem/Motivation

Unable to connt to IDE with log getting stuck at repeated log entry under `Addon\IDE  tab`

`INFO: Starting the NGINX daemon`

Here is the full addon log

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-hassio: applying... 
[fix-attrs.d] 10-hassio: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: IDE v0.5.1
 Advanced IDE for Home Assistant, based on Cloud9 IDE
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.10 / HA 0.77.3 / SU 131 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-link-common-dirs.sh: executing... 
[cont-init.d] 20-link-common-dirs.sh: exited 0.
[cont-init.d] 21-workspace.sh: executing... 
[cont-init.d] 21-workspace.sh: exited 0.
[cont-init.d] 22-user-settings.sh: executing... 
[cont-init.d] 22-user-settings.sh: exited 0.
[cont-init.d] 40-zsh.sh: executing... 
[cont-init.d] 40-zsh.sh: exited 0.
[cont-init.d] 50-user-ssh-folder.sh: executing... 
[cont-init.d] 50-user-ssh-folder.sh: exited 0.
[cont-init.d] 70-nginx.sh: executing... 
[cont-init.d] 70-nginx.sh: exited 0.
[cont-init.d] 80-user-packages.sh: executing... 
[cont-init.d] 80-user-packages.sh: exited 0.
[cont-init.d] 81-user-scripts.sh: executing... 
[cont-init.d] 81-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Starting the C9 server
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
Starting standalone
Connect server listening at http://127.0.0.1:80
Using basic authentication
CDN: version standalone initialized /cloud9/build
INFO: Starting the NGINX daemon
Started '/cloud9/configs/standalone' with config 'standalone'!
Cloud9 is up and running
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
INFO: Starting the NGINX daemon
```

Here is the log from `System` tab

```
18-09-22 04:42:15 INFO (SyncWorker_0) [hassio.docker.interface] Clean hassioaddons/ide-armhf docker application
18-09-22 04:42:25 INFO (SyncWorker_7) [hassio.docker.addon] Start docker addon hassioaddons/ide-armhf with version v0.5.1
18-09-22 04:42:34 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_ide/info no role for a0d7b954_ide
18-09-22 04:42:36 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_ide/info no role for a0d7b954_ide
18-09-22 04:42:38 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_ide/info no role for a0d7b954_ide
18-09-22 04:42:39 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_ide/info no role for a0d7b954_ide
18-09-22 04:42:49 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_ide/info no role for a0d7b954_ide
18-09-22 04:42:57 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_ide
18-09-22 04:43:15 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_ide/info no role for a0d7b954_ide
18-09-22 04:43:17 WARNING (MainThread) [hassio.api.security] /addons/a0d7b954_ide/info no role for a0d7b954_ide
```

```
HASSIO Version: 0.77.3
HASSOS Version: 1.10
```

## Expected behavior

Run and be able to connect on port `8321`

## Actual behavior

Unable to connect to port `8321`

## Steps to reproduce

Install `IDE` addon. I'm using following config

```
{
  "log_level": "info",
  "username": "admin",
  "password": "@dmin14",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "packages": [],
  "init_commands": []
}
```

Default port `8321`
Press start. Try to connect to `http://hassioip:8321`

## Proposed changes

N/A

**Comment by mayankraichura** [comment]
Upgraded HASSIO to `0.78.1` but the problem still persists.

**Comment by tjorim** [comment]
Hi, I don't use this add-on myself but the logs seem fine.
One thing I notice: you set `"ssl": true` in the config but are trying to connect to 'http://hassioip:8321', since ssl is enabled you would need to use httpS!

**Comment by mayankraichura** [comment]
Hi. I've tried both variants. With **s** and without **s**. However, please look at attached picture. The addon is stuck at starting NGINX. I've tried reinstalling the add-on without success.

![home assistant 1](https://user-images.githubusercontent.com/2023368/46039661-ed130000-c12b-11e8-804c-ce941b62af70.png)


> Hi, I don't use this add-on myself but the logs seem fine.
> One thing I notice: you set `"ssl": true` in the config but are trying to connect to 'http://hassioip:8321', since ssl is enabled you would need to use httpS!

**Comment by mpgoebel** [comment]
I am seeing the same thing.

**Comment by frenck** [comment]
Thank you all for the report, nevertheless, there is nothing in here that could be related.

For example, this add-on does not use or rely on Home Assistant, so, whatever your Home Assistant version is, it doesn't matter. As a matter of fact, the add-on can even run without Home Assistant.

Could anybody with this behavior try to start the add-on with `"log_level": "debug",` in their add-on options and tell me if alternative output is show when the `INFO: Starting the NGINX daemon` starts to happen?

Secondly, please provide some more add-on start banners. All version information I need in is there.

With the current information, there is nothing I can do.

**Comment by mpgoebel** [comment]
> INFO: Starting the NGINX daemon
> 2018/09/27 10:40:28 [notice] 749#749: using the "epoll" event method
> 2018/09/27 10:40:28 [notice] 749#749: nginx/1.14.0
> 2018/09/27 10:40:28 [notice] 749#749: OS: Linux 4.14.67
> 2018/09/27 10:40:28 [notice] 749#749: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> 2018/09/27 10:40:28 [notice] 749#749: start worker processes
> 2018/09/27 10:40:28 [notice] 749#749: start worker process 806

![image](https://user-images.githubusercontent.com/32761115/46157850-3f464500-c242-11e8-8c96-e9ffaca8f608.png)

I hope this is what you were wanting.

**Comment by mpgoebel** [comment]
I tried opening the webgui last night and it works locally with the local IP address but it just hangs with nothing appearing on screen with the external address. 

I also confirmed that my port forwarding was correct.

**Comment by mayankraichura** [comment]
[Update]
It seems it was a corrupted SD card. I reformatted the whole SD card using SD Card association formatter with a full rewrite format. After that, I reinstalled HASSOS/HASSIO and was able to install and run IDE add-on.

@frenck I guess can close this issue if you think there is no further need to keep it open.

**Comment by frenck** [comment]
👍
