### ISSUE TITLE
SSL certificates in different location

### ISSUE THREAD

**Issue by GJurriens** [hassio-addons/addon-ide#26]
# Problem/Motivation

> I can not seem to use ssl certificates generated by the NGINX proxy.

## Expected behavior

> I would like to be able to use the NGINX proxy generated ssl certificates.

## Actual behavior

> Certificate is not found, so the plugin does not start when trying to use a secure connection.

## Steps to reproduce

> Save the certificate files in (for example) /ssl/letsencrypt/live/hass/ and try starting the plugin.

## Proposed changes

> I would like to also have the option to provide full paths to the config, or a relative location to the certificates (ex. letsencrypt/live/hass/fullchain.pem).

**Comment by GJurriens** [comment]
Just to make sure... the NGINX proxy addon used is: https://github.com/bestlibre/hassio-addons/tree/master/nginx_proxy

<blockquote><img src="https://avatars1.githubusercontent.com/u/621360?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/bestlibre/hassio-addons">bestlibre/hassio-addons</a></strong></div><div>Contribute to bestlibre/hassio-addons development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
All community add-ons expect the SSL certificates to be in `/ssl/` as documented and as generated by the official Hass.io add-ons.

This is not something I'm going to change (especially, since Hass.io plans on changing the way it handles SSL certificates). At this point, I want to ensure compatibility for the near future.

**Comment by GJurriens** [comment]
Do you have a suggestion for a (temporary) work around?
Or provide some info on the certificate path Hass.io is going to take?

Either one of the above options will allow me continue (either using the work around or asking the dev of the other addon for a change).

**Comment by frenck** [comment]
As a workaround, I guess you could make a symlink?

As for the path Hass.io takes, not entirely sure... It is in early development stages and I don't want to drop stuff that might not be going to happen.

**Comment by GJurriens** [comment]
Oke, I'll try the symlinks.
Thanks for your time and fast responses.
