### ISSUE TITLE
Problem - PANIC: unprotected error in call to Lua API (bad light userdata pointer)

### ISSUE THREAD

**Issue by MadDoct** [hassio-addons/addon-ide#29]
# Problem/Motivation

> Can´t use the add-on

## Expected behavior

> Should run without errors

## Actual behavior
```
INFO: Starting the NGINX daemon
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
```
## Steps to reproduce

> arm64 version of the add-on - probably related to that...

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Thanks for the issue, unfortunately, at this point there is nothing I can do, since this is an upstream issue, without a workaround at this moment.
Awaiting updates.
