### ISSUE TITLE
Getting IDE working through nginx proxy pass 

### ISSUE THREAD

**Issue by ljmerza** [hassio-addons/addon-ide#31]
# Problem/Motivation
Instead of using the ide config for certs I want to use my nginx to config a reverse proxy to the ide server. I have certs setup through nginx. My nginx config file is:

```
location /ide {
        proxy_pass http://localhost:8321/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
}
```

then my hass config is:

```
panel_iframe:
  ide:
    title: 'IDE'
    icon: mdi:code-braces
    url: https://hass.example.com/ide
```

It wont work this way though. I assume its having to do with the /ide path. For Node-red I had to add to add the extra path to the config to get it work but how would the ide know I'm trying to server it under /ide? If I go to the ide directly from the local network via hass_ip_address:8321 then it works just fine.

my ide config:

```
{
  "log_level": "info",
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "packages": [],
  "init_commands": []
}
```

**Comment by frenck** [comment]
Sorry, can't help you there m8.
Making it compatible with all kinds of applications out there, is not a goal of the add-on.
This is solvable via the reverse proxy itself (hint `sub_filter`).
