### ISSUE TITLE
Dragdrop issue

### ISSUE THREAD

**Issue by dutchmhk** [hassio-addons/addon-ide#38]
# Problem/Motivation
Dragging a *.tar file from windows7 to IDE works, but gets deleted instantly afterward by IDE.
But dragging lets say a text file or yaml file, works perfectly. Tried renaming a .tar file to .txt, but still got deleted.
> (Why the issue was filed)
[log.txt](https://github.com/hassio-addons/addon-ide/files/3107106/log.txt)

## Expected behavior
Drag-drop should hopefully work in general It's a great feature and it works flawlessly in 0.8.0
I have 0.8.0 running on one instance and 1.0 on another. 
> (What you expected to happen)

## Actual behavior

> (What actually happened)
.tar file gets deleted instantly 
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
please fix this GREAT tool and btw - you guys are the greatest!! Without minds and skills like yours, and your contributions, I would still be in the stone age
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by dutchmhk** [comment]
"maybe" added bonus...
It looks as if it's file size dependent - observations are that anything above 10mb gets deleted and anything below 10mb is allowed/kept

**Comment by frenck** [comment]
Hmm, this might be related to file size. Could you test with a smaller file? (let's say 500kb?)

**Comment by frenck** [comment]
No response, closing issue.
