### ISSUE TITLE
Right click download folder will download .tar.gz issue in macOS

### ISSUE THREAD

**Issue by jerrychong25** [hassio-addons/addon-ide#40]
# Problem/Motivation

In macOS (Version 10.14.4), after opened Cloud IDE in Google Chrome Version 74.0.3729.157 (Official Build) (64-bit), when you right click and download folder (In this case: **config** folder), it will download **config.tar.gz** folder to PC, as per screenshot below:
<img width="304" alt="Screenshot 2019-05-15 at 11 37 26 PM" src="https://user-images.githubusercontent.com/15714095/57789164-f4465700-776a-11e9-9522-4bffd9193ebc.png">

After I opened the file with KeKa, it will have following error:
<img width="576" alt="Screenshot 2019-05-15 at 11 32 29 PM" src="https://user-images.githubusercontent.com/15714095/57789120-de389680-776a-11e9-8ccd-78cce299aafd.png">

This issue cannot be reproduced on Windows 7 Google Chrome Version 74.0.3729.157 (Official Build) (64-bit).

## Expected behavior

Download **config.tar.zip** into PC similar to Windows Based Google Chrome.

## Actual behavior

Download **config.tar.gz** into PC.

## Steps to reproduce

1) Open Google Chrome in macOS.
2) Open Cloud IDE of HA.
3) Right click on one of the folder (Example: **config**) and select **Download**.
4) **config.tar.gz** will be download into PC (Download URL: http://IP:8123/vfs/1/9cRfu6nYdlD7JfZi/workspace/share/?download=share.tar.gz).
5) Copy config.tar.gz download link and change from .gz to .zip (Download URL: http://IP:8123/vfs/1/9cRfu6nYdlD7JfZi/workspace/share/?download=share.tar.zip), then **config.tar.zip** will be download into PC.
6) Use KeKa to open **config.tar.gz**, unable to read the content of file. But can open **config.tar.zip** successfully.

## Proposed changes

Download **XXX.tar.zip** directly when user select Download for respective folder.

**Comment by jerrychong25** [comment]
> 👋 Thanks for opening your first issue here! If you're reporting a 🐛 bug, please make sure you include steps to reproduce it. Also, logs, error messages and information about your hardware might be usefull.

Included in the first post.

**Comment by frenck** [comment]
This is unfortunately not going to be fixed.
Cloud9 has been acquired by Amazon and the project has been left for dead. :(

If you can run the Visual Studio Code add-on, I would highly recommend it as a replacement.

**Comment by jerrychong25** [comment]
> This is unfortunately not going to be fixed.
> Cloud9 has been acquired by Amazon and the project has been left for dead. :(
> 
> If you can run the Visual Studio Code add-on, I would highly recommend it as a replacement.

Thanks for the info.

Unfortunately, Visual Studio Code can't run on my Raspberry Pi. (Reference: https://github.com/hassio-addons/addon-vscode/issues/33)

So, I don't have other option but to use Cloud9 IDE.
