### ISSUE TITLE
Include pylint

### ISSUE THREAD

**Issue by skylyn** [hassio-addons/addon-ide#41]
# Problem/Motivation

pylint saves time and encourages good, clean code

## Expected behavior

I write poorly formatted, or syntactically incorrect code, Cloud9 tells me with lint warnings/notices.

## Actual behavior

No pylint warning are shown

## Steps to reproduce

Write invalid python, wait for warnings.

## Proposed changes

Include pylint in C9 install.

**Comment by frenck** [comment]
pylint itself can be installed with the provided add-on options.
As for the IDE itself concerned: Cloud9 has been acquired by Amazon and they left the project for dead.
So, don't expect any new features in the future.

**Comment by skylyn** [comment]
Thanks Frenck. Appologies for the noob questions - I'm just getting started with Cloud9 and Hass.io. I did some searching but was unable to find instructions for installing pylint. Is there a guide you can point to? Or do I just need to put something in the packages config?

**Comment by skylyn** [comment]
I tried to install the alpine package py3-pylint, but when I restart the addon with that in the packages section of the config, I get this error:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-hassio: applying... 
[fix-attrs.d] 10-hassio: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: IDE
 Advanced IDE for Home Assistant, based on Cloud9 IDE
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.93.2
 Supervisor version: 166
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] c9.sh: executing... 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/armv7/APKINDEX.tar.gz
v3.9.4-24-g4e2ff29bbe [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.4-13-g22588a32d0 [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
v3.10.0_rc2-100-g250d19e252 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v3.10.0_rc2-130-g416c2dd2d0 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
v3.10.0_rc2-60-ga3df4f4cbf [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
OK: 23140 distinct packages available
ERROR: unsatisfiable constraints:
  readline-7.0.003-r1:
    conflicts: readline-8.0.0-r0
    satisfies: bash-4.4.19-r1[so:libreadline.so.7]
               sqlite-3.26.0-r3[so:libreadline.so.7]
               python2-2.7.15-r3[so:libreadline.so.7]
  readline-8.0.0-r0:
    masked in: @edge
    conflicts: readline-7.0.003-r1
    satisfies: python3-3.7.3-r0[so:libreadline.so.8]
  python3-3.7.3-r0:
    masked in: @edge
    satisfies: py3-wrapt-1.11.1-r0[python3]
               py3-wrapt-1.11.1-r0[so:libpython3.7m.so.1.0]
               py3-setuptools-40.6.3-r0[python3]
               py3-isort-4.3.4-r0[python3]
               py3-typed-ast-1.3.5-r0[python3]
               py3-typed-ast-1.3.5-r0[so:libpython3.7m.so.1.0]
               py3-lazy-object-proxy-1.4.1-r0[python3]
               py3-lazy-object-proxy-1.4.1-r0[so:libpython3.7m.so.1.0]
               py3-mccabe-0.6.1-r1[python3]
               py3-six-1.11.0-r0[python3]
  py3-lazy-object-proxy-1.4.1-r0:
    masked in: @edge
    satisfies: py3-astroid-2.2.5-r0[py3-lazy-object-proxy]
  py3-typed-ast-1.3.5-r0:
    masked in: @edge
    satisfies: py3-astroid-2.2.5-r0[py3-typed-ast]
  py3-wrapt-1.11.1-r0:
    masked in: @edge
    satisfies: py3-astroid-2.2.5-r0[py3-wrapt]
  py3-astroid-2.2.5-r0:
    masked in: @edge
    satisfies: py3-pylint-2.3.1-r0[py3-astroid]
  py3-pylint-2.3.1-r0:
    masked in: @edge
    satisfies: world[py3-pylint]
[22:46:36] FATAL: Failed installing package py3-pylint
[cont-init.d] c9.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
