### ISSUE TITLE
Adding an icon to be showed in the supervisor menu

### ISSUE THREAD

**Issue by sermayoral** [hassio-addons/addon-ide#44]
# Problem/Motivation

There is no problem, maybe a feature request?

## Expected behavior

I would like to see an icon in the supervisor menu. It's the only addon that does not have it.

## Actual behavior

The addon is deprecated, I know, but adding an icon does not cost anything, and it could make happy to all the Raspberry Pi 3 users who cannot use the vscode addon yet :-)

**Comment by frenck** [comment]
This addon does not receive any updates anymore, and will be removed from the addon store in the near future.

Sorry m8.
