### ISSUE TITLE
Download of folders not working in HASSIO. Zip utility missing from environment

### ISSUE THREAD

**Issue by slomanl1** [hassio-addons/addon-ide#5]
# Problem/Motivation
Download of folders not working in HASSIO.  Users need to have the ability to download their entire HASS configuration at once rather than one file at at time.,

## Expected behavior
Download a zip folder of the selected files/folders to the local machine

## Actual behavior
Received error message:
Precondition Failed - 412 - standalone Your instance seems to be missing the 'zip' utility If you are using an SSH workspace, please do: 'sudo apt-get install zip'

## Steps to reproduce
> (How can someone else make/see it happen)
Right click on a folder in the file tree and select "Download"

## Proposed changes
Add the zip utility to the add-on so Python environment in HASSIO can use it. HASSIO does not allow root access with SSH for adding applications. "sudo apt-get install" not allowed

**Comment by frenck** [comment]
Thank you for reporting this one!

**Comment by slomanl1** [comment]
Is it possible to configure the Cloud9 IDE in HASSIO with github to allow push and pull from repositories for backup? I do not see the instructions anywhere. It is not clear whether the AWS Cloud Services can accomplish that as well.

**Comment by hansbickhofe** [comment]
My Quick workaround for this:
- Open Terminal within the IDE
- "npm install zip"
The created zip is a little bit strange, but downloads are possible.

**Comment by frenck** [comment]
Fixed! Just released v0.3.0 which addresses this issue.

Thank you for the report.
