### ISSUE TITLE
Unable to install / upgrade to  IDE 2.0 error  Addon a0d7b954_ide not supported on armhf

### ISSUE THREAD

**Issue by bagobones** [hassio-addons/addon-ide#7]
# Problem/Motivation

Unable to install / upgrade to  IDE 2.0 error  Addon a0d7b954_ide not supported on armhf

## Expected behavior

Expected add-on to install / be supported on regular RASPBERRY PI 3 MODEL B not the plus

## Actual behavior

Nothing in the GUI really, just the error "ERROR (MainThread) [hassio.addons.addon] Addon a0d7b954_ide not supported on armhff" in the system log

## Steps to reproduce

Attempt to install the add on.

Hardware
serial:
/dev/ttyAMA0
/dev/ttyACM0
input:
disk:
gpio:
gpiochip0
gpiochip100
audio:
0:
name: bcm2835 - bcm2835 ALSA
type: ALSA
devices:
0: digital audio playback
1: digital audio playback

Version | 103.3
Latest version | 103.3

**Comment by lobradov** [comment]
was just coming here to report the same issue (or a feature request) - arm support (both -hf and -64) is missing.

**Comment by dishuostec** [comment]
I noticed support for armhf and aarch64 was recently droped:
https://github.com/hassio-addons/addon-ide/commit/f274771052850bd035eda6c7a672b4319f928dec

I have to use official addon "Configurator".

**Comment by frenck** [comment]
Hi there,

Support for ARM-based architectures has been dropped.
Please read the official announcement for more information:

https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/frenck/200/13184_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck">Community Hass.io Add-on: IDE, based on Cloud9</a></strong></div><div>🎉 Release v0.2.0 This release is exciting, at least, for me it is. I’ve been working on this for months! And for you? Well, a couple of things…  So what did change? I’ve updated the workflows of the Community Hass.io Add-ons project. Things include:   Replaced CircleCI and CodeClimate. We are now using GitLab CI, backed by a couple of custom servers building and testing these add-ons. All add-ons are now scanned during built and release by Clair to prevent security issues in our add-ons. A...</div></blockquote>

**Comment by lobradov** [comment]
pitty :/

I'll challenge you on the main thread and would offer my help to speed up ARM builds and integrate them into CI you are using - I understood that's your main pain.
