### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by smccloud** [hassio-addons/addon-ide#8]
# Problem/Motivation

I upload my sanitized config files to GitHub (i.e. I use secrets.yaml a lot and don't push it) and I'd love to not have to open the terminal addon to be able to add, commit & push changes.

## Expected behavior

Git integration for at least add, commit & push

## Actual behavior

No Git integration

## Steps to reproduce

Search for Git integration in the settings

## Proposed changes

No clue

**Comment by frenck** [comment]
Hi there,

Thank you for your request, nevertheless, this already exists...

![image](https://user-images.githubusercontent.com/195327/40184318-364cdee2-59f0-11e8-90cc-68a9e3848c60.png)

Closing this request for obvious reasons...

**Comment by smccloud** [comment]
Well, then I'm just blind today.  How about some documentation on how to set it up since that I cannot figure out.

**Comment by frenck** [comment]
Hi @smccloud,

The add-on documentation is about getting the add-on running and configured. For more information about the Cloud9 IDE, please refer to the official Could9 website & documentation.

../Frenck
