### ISSUE TITLE
Getting 400 error when trying to install

### ISSUE THREAD

**Issue by rkpatel33** [hassio-addons/addon-ide#9]
# Problem/Motivation

When I try to add the repo in the add-on store using this url:

https://github.com/hassio-addons/repository

I get  a 400 error on the POST. 
![image](https://user-images.githubusercontent.com/3799489/40271566-8e988a2e-5b53-11e8-9567-b15f7475b5b3.png)

When I click "Install" on the Hass.io add-in store, I get a 400 error in the console and add-on does not install.

![image](https://user-images.githubusercontent.com/3799489/40271457-883debe8-5b52-11e8-8f87-8dee66b4a592.png)

## Expected behavior

Add-on would install   properly and allow settings editing and start/restart like normal.

## Actual behavior

400 Error per above.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Could you please provide some system log output?

**Comment by rkpatel33** [comment]
I don't really see anything being printed to the `home-assistant.log` file:

```
2018-05-19 10:56:14 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 308, in _async_add_entity
    msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: automation.notify_on_arrive_router
2018-05-19 10:56:23 WARNING (MainThread) [homeassistant.setup] Setup of config is taking over 10 seconds.
2018-05-19 10:56:48 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
```

I also restarted and tried again for good measure but did no dice.

**Comment by rkpatel33** [comment]
So looks like I am getting 400 or 404 error for all the:

```
http://hassio.local:8123/api/hassio/* 
```

Endpoint so I can't install any add-ons. Not sure what is causing this all of a sudden. Pls let me know if you have any suggestions but will post this on the hass.io issues as well.

![image](https://user-images.githubusercontent.com/3799489/40271691-9e566178-5b55-11e8-8130-18afd9e9aa39.png)

**Comment by rkpatel33** [comment]
Apologies for the multiple posts. I just confirmed I am able to install other add-ons, so it the issue looks specific to this add-on. I forgot I had already added the community add-on repo to my add-on store.

**Comment by frenck** [comment]
@rkpatel33 Not the Home Assistant logfile, but the Hass.io System log file.
You can find this one under Hass.io -> System.

**Comment by rkpatel33** [comment]
Apologies, here is the hass.io log, the last line is what appeared after I clicked install:

```
18-05-19 19:25:42 INFO (MainThread) [hassio.updater] Fetch update data from https://raw.githubusercontent.com/home-assistant/hassio/master/version.json
18-05-19 19:25:42 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/home-assistant/hassio-addons repository
18-05-19 19:25:42 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/hassio-addons/repository repository
18-05-19 19:25:43 INFO (MainThread) [hassio.addons] Load addons: 34 all - 0 new - 0 remove
18-05-19 20:04:26 ERROR (MainThread) [hassio.addons.addon] Addon a0d7b954_ide not supported on armhf
```

**Comment by frenck** [comment]
`Addon a0d7b954_ide not supported on armhf`

The add-on is no longer available/supported on ARM-based devices (e.g., Raspberry Pi).
For more information about this, read the official statement:

https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck


<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/frenck/200/13184_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck">Community Hass.io Add-on: IDE, based on Cloud9</a></strong></div><div>🎉 Release v0.2.0 This release is exciting, at least, for me it is. I’ve been working on this for months! And for you? Well, a couple of things…  So what did change? I’ve updated the workflows of the Community Hass.io Add-ons project. Things include:   Replaced CircleCI and CodeClimate. We are now using GitLab CI, backed by a couple of custom servers building and testing these add-ons. All add-ons are now scanned during built and release by Clair to prevent security issues in our add-ons. A...</div></blockquote>
